import {question} from '../model/types';

export const questions: Record<string, question> = {
    q1:{id:'q1', text:`I have a high level of physical energy`, axis:'PhysicalHealth', score:0},
    q2:{id:'q2', text:`When I wake up, I feel rested and ready for a new day`, axis:'PhysicalHealth', score:0},
    q3:{id:'q3', text:`I like exercising and do so regularly every week`, axis:'PhysicalHealth', score:0},
    q4:{id:'q4', text:`My eating and drinking habits are healthy`, axis:'PhysicalHealth', score:0},
    q5:{id:'q5', text:`My routines for exercising are well set up`, axis:'PhysicalHealth', score:0},
    q6:{id:'q6', text:`I have regular ‘rests’ where I take time to relax and do my favourite thing(s)`, axis:'PhysicalHealth', score:0},
    q7:{id:'q7', text:`I sleep at least seven hours most days`, axis:'PhysicalHealth', score:0},
    q8:{id:'q8', text:`I feel fit and healthy`, axis:'PhysicalHealth', score:0},
    q9:{id:'q9', text:`I have activities that help me recharge my batteries`, axis:'PhysicalHealth', score:0},
    q10:{id:'q10', text:`I find it easy to concentrate and focus on my work`, axis:'CognitiveHealth', score:0},
    q11:{id:'q11', text:`I manage my time effectively and well`, axis:'CognitiveHealth', score:0},
    q12:{id:'q12', text:`I have a positive outlook on life`, axis:'CognitiveHealth', score:0},
    q13:{id:'q13', text:`I try to find solutions to problems and issues`, axis:'CognitiveHealth', score:0},
    q14:{id:'q14', text:`I can easily switch off when I take a break or in the evening`, axis:'CognitiveHealth', score:0},
    q15:{id:'q15', text:`I don’t overthink or overanalyze things`, axis:'CognitiveHealth', score:0},
    q16:{id:'q16', text:`I can recognize and name many of the emotions I experience (positive and negative)`, axis:'EmotionalHealth', score:0},
    q17:{id:'q17', text:`I am happy with all my emotions (negative and positive) and welcome them`, axis:'EmotionalHealth', score:0},
    q18:{id:'q18', text:`I can regulate my emotions and can express them in a healthy way`, axis:'EmotionalHealth', score:0},
    q19:{id:'q19', text:`I feel connected to others and know who to reach out to when I am feeling sad or upset`, axis:'EmotionalHealth', score:0},
    q20:{id:'q20', text:`I create good relationships with others`, axis:'SocialHealth', score:0},
    q21:{id:'q21', text:`I get along with my friends`, axis:'SocialHealth', score:0},
    q22:{id:'q22', text:`I get along with my family`, axis:'SocialHealth', score:0},
    q23:{id:'q23', text:`I feel confident`, axis:'SocialHealth', score:0},
    q24:{id:'q24', text:`I enjoy speaking in public`, axis:'SocialHealth', score:0},
    q25:{id:'q25', text:`I have good friends with whom I can share my issues easily`, axis:'SocialHealth', score:0},
    q26:{id:'q26', text:`I can manage conflict and focus on getting everyone’s needs met`, axis:'SocialHealth', score:0},
    q27:{id:'q27', text:`I have a passion/hobby I engage with on a regular basis`, axis:'SpiritualHealth', score:0},
    q28:{id:'q28', text:`I know what I want to achieve in life`, axis:'SpiritualHealth', score:0},
    q29:{id:'q29', text:`I have a sense of purpose in life`, axis:'SpiritualHealth', score:0},
    q30:{id:'q30', text:`I know what my personal values are in life`, axis:'SpiritualHealth', score:0},
    q31:{id:'q31', text:`I set goals which are aligned with my personal values`, axis:'SpiritualHealth', score:0},
    q32:{id:'q32', text:`I have a fulfilling life`, axis:'SpiritualHealth', score:0},
    q33:{id:'q33', text:`I enjoy reconnecting to nature on a regular basis`, axis:'SpiritualHealth', score:0},
    q34:{id:'q34', text:`I believe I am learning and growing every day`, axis:'SpiritualHealth', score:0},
    q35:{id:'q35', text:`I believe I am a compassionate human being`, axis:'SpiritualHealth', score:0},
}
